language: node_js
node_js: '9'
services:
- postgresql
before_script:
- psql -c 'create database palette;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: EXaqSojS3U0SVCZEqvRebQmVbRa3HM4UZdok6UZZkQBB9Z5geUVbKGYr8mLgCwchq+vizyqoMboZJ8vuXWTRR0fIoiDJif+7Eu5cWSdVi9ysMTvVtP19GH1+vvWWpz3eT8ihb1t+AmbrU6o0dJKIRtaI5sYNX3JcPQuyjTF2LdH35jIU00PsNsuLgQYS9j6ddBl7u01GXk5WamZ17O4ieVwjyLeZ+7itp5LliNVx2AhSYhvR8vFGIdGnFSAJxHgSlGM+jGOMrxmlmRWf1bdG7IG+dyvwpcispAXFgkl9q29Ux5tJCGnuo1q/StXz1jh4unZkufLLwCEB1N2mNlSftuQKD06tUcjQOWDtH6hjSEfp8Z/nftVFIeFgftoXDkMDWr4EHBCGMwOpJLHnaeZNXN2GHpLFLJiezOeG6lela2iHHJAetrxTCYZHr9OrtVSMs/Q1Vdk3wsd4cDPfG0bzyFl7cZQAR2QEAFLl8qJE7MG8qaijcRH3jZEWRO3pTfD4h5397R61zfpsXITB3cPOuD0EN605vZkQAiwkiZjTN3v/rbwZh1VpQi5LM4sten86wEvp0ekbhYoyRpyYCNbPchHlJrt3lNSKbB3VV+ohwFqViVmYQZ0Ch6a3gZb2xSwrDf+hQbOy3DWreOueOmSOLgRpslDVG5vZn/a6kqv10vs=
  app: mellow-palette-picker
  skip_cleanup: true
